<template><div class="page-container" v-loading="loading"><div class="page-header header"><div><h1 class="page-title">数据分析</h1><p class="page-subtitle">基于库存流水和已完成业务单据的运营分析</p></div><el-radio-group v-model="days" @change="load"><el-radio-button :value="7">7天</el-radio-button><el-radio-button :value="30">30天</el-radio-button><el-radio-button :value="90">90天</el-radio-button></el-radio-group></div><el-result v-if="failed" icon="error" title="分析数据加载失败"><template #extra><el-button type="primary" @click="load">重新加载</el-button></template></el-result><div v-else class="charts"><div class="card chart"><div class="title">库存趋势</div><v-chart :option="trendOption" autoresize/></div><div class="card chart"><div class="title">SKU ABC分类</div><v-chart :option="abcOption" autoresize/></div><div class="card chart"><div class="title">库存周转率</div><v-chart :option="turnoverOption" autoresize/></div><div class="card chart"><div class="title">Top出库商品</div><v-chart :option="topOption" autoresize/></div></div></div></template>
<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import VChart from'vue-echarts';import{use}from'echarts/core';import{CanvasRenderer}from'echarts/renderers';import{LineChart,PieChart,BarChart}from'echarts/charts';import{GridComponent,TooltipComponent,LegendComponent,DataZoomComponent}from'echarts/components';import{analyticsApi}from'@/api';use([CanvasRenderer,LineChart,PieChart,BarChart,GridComponent,TooltipComponent,LegendComponent,DataZoomComponent]);
const days=ref(30),loading=ref(false),failed=ref(false),data=ref<any>({trend:{dates:[],total:[],available:[]},abc:[],turnover:{months:[],values:[]},topProducts:[]});
const baseGrid={left:'3%',right:'4%',bottom:'12%',containLabel:true};
const trendOption=computed(()=>({tooltip:{trigger:'axis'},legend:{data:['库存总量','可用库存']},grid:baseGrid,xAxis:{type:'category',data:data.value.trend.dates},yAxis:{type:'value'},dataZoom:data.value.trend.dates.length>30?[{type:'inside'},{type:'slider',height:18}]:[],series:[{name:'库存总量',type:'line',smooth:true,showSymbol:false,data:data.value.trend.total},{name:'可用库存',type:'line',smooth:true,showSymbol:false,data:data.value.trend.available}]}));
const abcOption=computed(()=>({tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['42%','70%'],label:{formatter:'{b}\n{c} 个SKU'},data:data.value.abc}]}));
const turnoverOption=computed(()=>({tooltip:{trigger:'axis',valueFormatter:(v:any)=>`${v} 次`},grid:baseGrid,xAxis:{type:'category',data:data.value.turnover.months},yAxis:{type:'value',name:'周转次数'},series:[{type:'bar',barMaxWidth:38,data:data.value.turnover.values,itemStyle:{color:'#2563eb',borderRadius:[5,5,0,0]}}]}));
const topOption=computed(()=>{const rows=[...data.value.topProducts].reverse();return{tooltip:{trigger:'axis'},grid:{left:'3%',right:'8%',bottom:'3%',containLabel:true},xAxis:{type:'value'},yAxis:{type:'category',data:rows.map((x:any)=>x.productName||x.skuCode)},series:[{type:'bar',data:rows.map((x:any)=>x.quantity),label:{show:true,position:'right'},itemStyle:{color:'#16a34a',borderRadius:[0,5,5,0]}}]}});
async function load(){loading.value=true;failed.value=false;try{const r=await analyticsApi.getAnalytics(days.value);data.value=r.data||data.value}catch{failed.value=true}finally{loading.value=false}}onMounted(load)
</script>
<style scoped>.header{display:flex;align-items:center;justify-content:space-between}.charts{display:grid;grid-template-columns:1fr 1fr;gap:20px}.chart{height:380px;display:flex;flex-direction:column}.chart :deep(.echarts){flex:1;min-height:0}.title{font-size:16px;font-weight:600;margin-bottom:12px}@media(max-width:1000px){.charts{grid-template-columns:1fr}}</style>
