<template>
  <div class="page-container ai-page">
    <aside class="history-panel"><el-button type="primary" class="new-chat" @click="newChat"><el-icon><Plus/></el-icon>新对话</el-button><div class="history-title">历史对话</div><button v-for="item in conversations" :key="item.conversationId" class="history-item" :class="{active:item.conversationId===conversationId}" @click="selectConversation(item)"><span>{{item.title||'新对话'}}</span><small>{{formatTime(item.updatedAt)}}</small></button><el-empty v-if="!conversations.length" :image-size="60" description="暂无历史对话"/></aside>
    <section class="ai-container">
      <div class="ai-header"><h1 class="ai-title">Warehouse Copilot</h1><p class="ai-subtitle">基于仓储真实数据提供运营分析</p></div>
      <div v-if="!messages.length" class="quick-actions"><el-button v-for="action in quickActions" :key="action.label" @click="quickAsk(action.prompt)">{{action.label}}</el-button></div>
      <div ref="chatAreaRef" class="chat-area" v-loading="historyLoading"><el-empty v-if="!messages.length&&!historyLoading" description="选择快捷问题或直接开始对话"/><div v-for="msg in messages" :key="msg.id||`${msg.role}-${msg.createdAt}-${msg.content}`" :class="['message',msg.role]"><div class="message-avatar"><el-avatar :size="36" v-if="msg.role==='user'">我</el-avatar><el-avatar v-else :size="36" class="ai-avatar">AI</el-avatar></div><div class="message-content">{{msg.content}}</div></div><div v-if="loading" class="message assistant"><div class="message-avatar"><el-avatar :size="36" class="ai-avatar">AI</el-avatar></div><div class="message-content thinking">正在分析仓储数据<span>...</span></div></div></div>
      <div class="input-area"><el-input v-model="inputMessage" type="textarea" :autosize="{minRows:2,maxRows:5}" resize="none" placeholder="输入仓储问题，Ctrl + Enter 发送" :disabled="loading" @keydown.ctrl.enter.prevent="sendMessage"/><el-button type="primary" :loading="loading" :disabled="!inputMessage.trim()" @click="sendMessage">发送</el-button></div>
    </section>
  </div>
</template>
<script setup lang="ts">
import { nextTick,onMounted,ref } from 'vue';import { ElMessage } from 'element-plus';import { Plus } from '@element-plus/icons-vue';import { aiApi } from '@/api'
const chatAreaRef=ref<HTMLElement>();const inputMessage=ref('');const loading=ref(false);const historyLoading=ref(false);const messages=ref<any[]>([]);const conversations=ref<any[]>([]);const conversationId=ref('')
const quickActions=[{label:'库存风险分析',prompt:'分析目前哪些商品存在缺货风险'},{label:'查库存',prompt:'查询各仓库的库存情况'},{label:'分析出库',prompt:'过去一个月出库量最大的商品是什么'},{label:'仓库利用率',prompt:'各仓库的利用率分别是多少'},{label:'临期商品',prompt:'哪些商品将在一个月内过期'}]
const scrollBottom=()=>nextTick(()=>{if(chatAreaRef.value)chatAreaRef.value.scrollTop=chatAreaRef.value.scrollHeight});const formatTime=(v:string)=>v?new Date(v).toLocaleDateString('zh-CN'):''
const loadConversations=async()=>{try{conversations.value=(await aiApi.getConversations()).data||[]}catch{conversations.value=[]}}
const newChat=()=>{conversationId.value='';messages.value=[];inputMessage.value=''}
const selectConversation=async(item:any)=>{if(loading.value)return;conversationId.value=item.conversationId;historyLoading.value=true;try{messages.value=(await aiApi.getMessages(item.conversationId)).data||[];scrollBottom()}finally{historyLoading.value=false}}
const ensureConversation=async(title:string)=>{if(conversationId.value)return;const res=await aiApi.createConversation(title.slice(0,50));conversationId.value=res.data.conversationId}
const sendMessage=async()=>{const content=inputMessage.value.trim();if(!content||loading.value)return;loading.value=true;try{await ensureConversation(content);messages.value.push({role:'user',content,createdAt:new Date().toISOString()});inputMessage.value='';scrollBottom();const res=await aiApi.chat({conversationId:conversationId.value,message:content});messages.value.push(res.data);await loadConversations()}catch(e:any){ElMessage.error(e?.message||'AI请求失败')}finally{loading.value=false;scrollBottom()}}
const quickAsk=(prompt:string)=>{inputMessage.value=prompt;sendMessage()};onMounted(loadConversations)
</script>
<style scoped>
.ai-page{height:calc(100vh - 104px);display:grid;grid-template-columns:240px minmax(0,1fr);gap:16px}.history-panel,.chat-area{background:#fff;border:1px solid var(--border-color);border-radius:12px}.history-panel{padding:14px;overflow-y:auto}.new-chat{width:100%;margin-bottom:18px}.history-title{font-size:13px;color:var(--text-secondary);margin:0 8px 8px}.history-item{display:flex;flex-direction:column;gap:5px;width:100%;border:0;background:transparent;border-radius:7px;padding:10px;text-align:left;cursor:pointer;color:var(--text-body)}.history-item:hover,.history-item.active{background:var(--el-color-primary-light-9);color:var(--el-color-primary)}.history-item span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;width:100%}.history-item small{color:var(--text-secondary)}.ai-container{min-width:0;display:flex;flex-direction:column}.ai-header{text-align:center;padding:10px 0 16px}.ai-title{font-size:26px;margin:0 0 6px}.ai-subtitle{font-size:14px;color:var(--text-secondary);margin:0}.quick-actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin-bottom:14px}.chat-area{flex:1;overflow-y:auto;padding:20px;margin-bottom:14px}.message{display:flex;gap:12px;margin-bottom:20px}.message.user{flex-direction:row-reverse}.message-content{max-width:72%;white-space:pre-wrap;padding:12px 16px;border-radius:12px;line-height:1.65}.message.user .message-content{background:#2563eb;color:#fff}.message.assistant .message-content{background:#f3f4f6;color:var(--text-body)}.ai-avatar{background:#2563eb}.thinking{color:var(--text-secondary)!important}.input-area{display:flex;align-items:flex-end;gap:12px;padding:0 4px}.input-area .el-button{height:54px;width:82px}@media(max-width:900px){.ai-page{grid-template-columns:1fr}.history-panel{display:none}}
</style>
