<template><div class="page-container" v-loading="loading"><div class="page-header header"><div><h1 class="page-title">调拨单详情</h1><p class="page-subtitle">查看并推进仓库间库存调拨</p></div><div class="actions"><el-button @click="router.back()">返回</el-button><el-button v-if="order.status==='CREATED'" type="primary" :loading="submitting" @click="approve">审核通过</el-button><el-button v-if="order.status==='APPROVED'" type="warning" :loading="submitting" @click="execute">执行调拨</el-button></div></div><el-result v-if="!loading&&failed" icon="error" title="加载失败"><template #extra><el-button type="primary" @click="load">重新加载</el-button></template></el-result><div v-else class="card"><el-descriptions :column="3" border><el-descriptions-item label="调拨单号">{{order.orderNo||'-'}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="status.type">{{status.text}}</el-tag></el-descriptions-item><el-descriptions-item label="总数量">{{order.totalQty??0}}</el-descriptions-item><el-descriptions-item label="源仓库">{{order.sourceWarehouseName||order.sourceWarehouseId||'-'}}</el-descriptions-item><el-descriptions-item label="目标仓库">{{order.targetWarehouseName||order.targetWarehouseId||'-'}}</el-descriptions-item><el-descriptions-item label="已接收">{{order.receivedQty??0}}</el-descriptions-item><el-descriptions-item label="备注" :span="3">{{order.remark||'-'}}</el-descriptions-item></el-descriptions><el-divider/><el-steps :active="step" finish-status="success" align-center class="steps"><el-step title="创建"/><el-step title="审核"/><el-step title="执行调拨"/><el-step title="完成"/></el-steps><div class="title">商品明细</div><el-table :data="items" border empty-text="暂无调拨明细"><el-table-column prop="skuCode" label="SKU" width="160"><template #default="{row}">{{row.skuCode||row.skuId}}</template></el-table-column><el-table-column prop="productName" label="商品" min-width="180"/><el-table-column prop="batchNo" label="批次" width="150"/><el-table-column prop="qty" label="计划数量" width="110" align="right"/><el-table-column prop="shippedQty" label="已发出" width="100" align="right"/><el-table-column prop="receivedQty" label="已接收" width="100" align="right"/><el-table-column prop="status" label="状态" width="110"/></el-table></div></div></template>
<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage,ElMessageBox}from'element-plus';import{transferApi}from'@/api';
const route=useRoute(),router=useRouter(),id=Number(route.params.id),loading=ref(false),submitting=ref(false),failed=ref(false),order=ref<Record<string,any>>({}),items=ref<any[]>([]),map:Record<string,any>={CREATED:{text:'待审核',type:'info',step:1},APPROVED:{text:'待执行',type:'warning',step:2},COMPLETED:{text:'已完成',type:'success',step:4},CANCELLED:{text:'已取消',type:'danger',step:0}};
const status=computed(()=>map[order.value.status]||{text:order.value.status||'-',type:'info',step:0}),step=computed(()=>status.value.step);
async function load(){loading.value=true;failed.value=false;try{const[o,i]=await Promise.all([transferApi.getTransferOrderById(id),transferApi.getTransferOrderItems(id)]);order.value=o.data||{};items.value=i.data||[]}catch{failed.value=true}finally{loading.value=false}}
async function run(fn:()=>Promise<any>,text:string){await ElMessageBox.confirm(`确认${text}该调拨单？`,text,{type:'warning'});submitting.value=true;try{await fn();ElMessage.success(`${text}成功`);await load()}finally{submitting.value=false}}
const approve=()=>run(()=>transferApi.approveTransferOrder(id),'审核')
const execute=()=>run(()=>transferApi.executeTransferOrder(id),'执行调拨')
onMounted(load)
</script>
<style scoped>.header,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}.steps{margin:10px 0 32px}.title{font-size:16px;font-weight:600;margin-bottom:16px}</style>
