<template><div class="page-container"><div class="page-header"><h1 class="page-title">调拨管理</h1><p class="page-subtitle">管理仓库间库存调拨业务</p></div><div class="card"><div class="search-bar"><el-input v-model="keyword" placeholder="搜索调拨单号" prefix-icon="Search" clearable @keyup.enter="loadData"/><el-select v-model="status" placeholder="状态" clearable style="width:130px"><el-option label="待审核" value="CREATED"/><el-option label="待执行" value="APPROVED"/><el-option label="已完成" value="COMPLETED"/></el-select><el-button type="primary" @click="loadData">查询</el-button><el-button type="success" @click="openCreate"><el-icon><Plus/></el-icon> 新建调拨单</el-button></div>
<el-table :data="rows" border stripe v-loading="loading" empty-text="暂无调拨单"><el-table-column prop="orderNo" label="调拨单号" width="170"/><el-table-column prop="sourceWarehouseName" label="源仓库" min-width="140"><template #default="{row}">{{row.sourceWarehouseName||row.sourceWarehouseId}}</template></el-table-column><el-table-column prop="targetWarehouseName" label="目标仓库" min-width="140"><template #default="{row}">{{row.targetWarehouseName||row.targetWarehouseId}}</template></el-table-column><el-table-column prop="totalQty" label="数量" width="90" align="right"/><el-table-column prop="receivedQty" label="已接收" width="90" align="right"/><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag :type="statusInfo(row.status).type">{{statusInfo(row.status).text}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button type="primary" link @click="router.push(`/transfer/${row.id}`)">详情</el-button><el-button v-if="row.status==='CREATED'" type="primary" link @click="approve(row)">审核</el-button><el-button v-if="row.status==='APPROVED'" type="warning" link @click="execute(row)">执行</el-button></template></el-table-column></el-table><el-pagination v-if="total>pageSize" v-model:current-page="page" :page-size="pageSize" :total="total" layout="total,prev,pager,next" class="pagination" @current-change="loadData"/></div>
<el-dialog v-model="dialog" title="新建调拨单" width="760px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><div class="grid"><el-form-item label="源仓库" prop="sourceWarehouseId"><el-select v-model="form.sourceWarehouseId" filterable><el-option v-for="w in warehouses" :key="w.id" :label="w.warehouseName" :value="w.id"/></el-select></el-form-item><el-form-item label="目标仓库" prop="targetWarehouseId"><el-select v-model="form.targetWarehouseId" filterable><el-option v-for="w in warehouses" :key="w.id" :label="w.warehouseName" :value="w.id" :disabled="w.id===form.sourceWarehouseId"/></el-select></el-form-item></div><el-form-item label="备注"><el-input v-model.trim="form.remark" type="textarea" maxlength="200" show-word-limit/></el-form-item><div class="items-title"><b>调拨明细</b><el-button type="primary" link @click="addItem"><el-icon><Plus/></el-icon>添加商品</el-button></div><div v-for="(item,index) in form.items" :key="item.key" class="item-row"><el-form-item label="SKU" :prop="`items.${index}.skuId`" :rules="[{required:true,message:'请选择SKU',trigger:'change'}]"><el-select v-model="item.skuId" filterable><el-option v-for="s in skus" :key="s.id" :label="`${s.skuCode} · ${s.productName||''} ${s.specification||''}`" :value="s.id"/></el-select></el-form-item><el-form-item label="数量" :prop="`items.${index}.qty`" :rules="[{required:true,message:'请输入数量',trigger:'blur'}]"><el-input-number v-model="item.qty" :min="1" :precision="0"/></el-form-item><el-button v-if="form.items.length>1" type="danger" link @click="form.items.splice(index,1)">删除</el-button></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">创建调拨单</el-button></template></el-dialog></div></template>
<script setup lang="ts">import{onMounted,reactive,ref}from'vue';import{useRouter}from'vue-router';import{ElMessage,ElMessageBox,type FormInstance,type FormRules}from'element-plus';import{Plus}from'@element-plus/icons-vue';import{transferApi,warehouseApi,productReferenceApi}from'@/api';
const router=useRouter(),rows=ref<any[]>([]),warehouses=ref<any[]>([]),skus=ref<any[]>([]),loading=ref(false),submitting=ref(false),dialog=ref(false),keyword=ref(''),status=ref(''),page=ref(1),pageSize=20,total=ref(0),formRef=ref<FormInstance>();let key=0;
const form=reactive({sourceWarehouseId:null as number|null,targetWarehouseId:null as number|null,remark:'',items:[]as Array<{key:number;skuId:number|null;qty:number}>}),rules:FormRules={sourceWarehouseId:[{required:true,message:'请选择源仓库',trigger:'change'}],targetWarehouseId:[{required:true,message:'请选择目标仓库',trigger:'change'}]},map:Record<string,any>={CREATED:{text:'待审核',type:'info'},APPROVED:{text:'待执行',type:'warning'},COMPLETED:{text:'已完成',type:'success'},CANCELLED:{text:'已取消',type:'danger'}};const statusInfo=(s:string)=>map[s]||{text:s,type:'info'};
async function loadData(){loading.value=true;try{const r=await transferApi.listTransferOrders({page:page.value,pageSize,keyword:keyword.value||undefined,status:status.value||undefined});rows.value=r.data?.records||[];total.value=r.data?.total||0}finally{loading.value=false}}const addItem=()=>form.items.push({key:++key,skuId:null,qty:1});
async function openCreate(){Object.assign(form,{sourceWarehouseId:null,targetWarehouseId:null,remark:''});form.items=[];addItem();dialog.value=true;try{const[w,s]=await Promise.all([warehouseApi.listWarehouses({page:1,pageSize:1000}),productReferenceApi.listSkus()]);warehouses.value=w.data?.records||w.data||[];skus.value=s.data||[]}catch{dialog.value=false}}
async function submit(){if(!await formRef.value?.validate())return;if(form.sourceWarehouseId===form.targetWarehouseId){ElMessage.warning('源仓库和目标仓库不能相同');return}const ids=form.items.map(x=>x.skuId);if(new Set(ids).size!==ids.length){ElMessage.warning('同一个SKU请合并为一行');return}submitting.value=true;try{await transferApi.createTransferOrder({order:{sourceWarehouseId:form.sourceWarehouseId,targetWarehouseId:form.targetWarehouseId,remark:form.remark},items:form.items.map(({skuId,qty})=>({skuId,qty}))});ElMessage.success('调拨单创建成功');dialog.value=false;page.value=1;await loadData()}finally{submitting.value=false}}
async function run(row:any,fn:()=>Promise<any>,text:string){await ElMessageBox.confirm(`确认对调拨单 ${row.orderNo} 执行${text}？`,text,{type:'warning'});await fn();ElMessage.success(`${text}成功`);await loadData()}
const approve=(r:any)=>run(r,()=>transferApi.approveTransferOrder(r.id),'审核')
const execute=(r:any)=>run(r,()=>transferApi.executeTransferOrder(r.id),'调拨')
onMounted(loadData)
</script>
<style scoped>.pagination{justify-content:flex-end;margin-top:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.grid :deep(.el-select),.item-row :deep(.el-select){width:100%}.items-title{display:flex;justify-content:space-between;align-items:center;margin:10px 0}.item-row{display:grid;grid-template-columns:minmax(0,2fr) minmax(180px,1fr) 48px;gap:12px;padding:12px;background:var(--el-fill-color-lighter);border-radius:8px;margin-bottom:10px}.item-row :deep(.el-form-item){margin-bottom:0}</style>
