<template>
  <div class="page-container">
    <div class="page-header"><h1 class="page-title">任务中心</h1><p class="page-subtitle">统一管理上架、拣货、盘点和补货任务</p></div>
    <div class="card">
      <el-tabs v-model="activeTab" @tab-change="changeTab"><el-tab-pane label="全部" name="all"/><el-tab-pane label="待分配" name="PENDING"/><el-tab-pane label="进行中" name="IN_PROGRESS"/><el-tab-pane label="已完成" name="COMPLETED"/></el-tabs>
      <div class="search-bar"><el-input v-model="keyword" placeholder="搜索任务号、来源单据或执行人" prefix-icon="Search" clearable @keyup.enter="search"/><el-select v-model="taskType" placeholder="任务类型" clearable style="width:130px"><el-option v-for="item in taskTypes" :key="item.value" :label="item.label" :value="item.value"/></el-select><el-button type="primary" @click="search">查询</el-button><el-button type="success" @click="openCreate"><el-icon><Plus/></el-icon>新建任务</el-button></div>
      <el-table :data="rows" stripe border v-loading="loading" empty-text="暂无任务">
        <el-table-column prop="taskNo" label="任务号" width="165"/><el-table-column label="类型" width="100"><template #default="{row}">{{typeText(row.taskType)}}</template></el-table-column><el-table-column prop="sourceOrderNo" label="来源单据" width="165"><template #default="{row}">{{row.sourceOrderNo||'-'}}</template></el-table-column><el-table-column label="仓库" min-width="130"><template #default="{row}">{{warehouseName(row.warehouseId)}}</template></el-table-column><el-table-column label="优先级" width="90"><template #default="{row}"><el-tag :type="priorityInfo(row.priority).type">{{priorityInfo(row.priority).text}}</el-tag></template></el-table-column><el-table-column prop="assigneeName" label="执行人" width="110"><template #default="{row}">{{row.assigneeName||'待分配'}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="statusInfo(row.status).type">{{statusInfo(row.status).text}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="175"/><el-table-column label="操作" width="130" fixed="right"><template #default="{row}"><el-button v-if="row.status==='PENDING'" type="success" link @click="openAssign(row)">分配</el-button><el-button v-if="row.status==='IN_PROGRESS'" type="warning" link @click="complete(row)">完成</el-button></template></el-table-column>
      </el-table><div class="pagination-wrapper"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[10,20,50]" :total="total" layout="total,sizes,prev,pager,next" @size-change="loadData" @current-change="loadData"/></div>
    </div>
    <el-dialog v-model="createVisible" title="新建任务" width="540px"><el-form :model="form" label-width="90px"><el-form-item label="任务类型" required><el-select v-model="form.taskType" style="width:100%"><el-option v-for="item in taskTypes" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item label="所属仓库" required><el-select v-model="form.warehouseId" filterable style="width:100%"><el-option v-for="item in warehouses" :key="item.id" :label="item.warehouseName" :value="item.id"/></el-select></el-form-item><el-form-item label="来源单据"><el-input v-model="form.sourceOrderNo"/></el-form-item><el-form-item label="优先级"><el-radio-group v-model="form.priority"><el-radio :value="0">普通</el-radio><el-radio :value="1">优先</el-radio><el-radio :value="2">紧急</el-radio></el-radio-group></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="createVisible=false">取消</el-button><el-button type="primary" :loading="submitting" @click="createTask">创建</el-button></template></el-dialog>
    <el-dialog v-model="assignVisible" title="分配任务" width="460px"><el-form label-width="80px"><el-form-item label="任务号">{{currentTask?.taskNo}}</el-form-item><el-form-item label="执行人" required><el-select v-model="assigneeId" filterable placeholder="选择启用用户" style="width:100%"><el-option v-for="user in users" :key="user.id" :label="`${user.realName||user.username}（${user.username}）`" :value="user.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="assignVisible=false">取消</el-button><el-button type="primary" :loading="submitting" @click="assign">确认分配</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { Plus } from '@element-plus/icons-vue';import { taskApi,userApi,warehouseApi } from '@/api'
const taskTypes=[{label:'上架',value:'PUTAWAY'},{label:'拣货',value:'PICKING'},{label:'盘点',value:'STOCKTAKE'},{label:'补货',value:'REPLENISHMENT'}]
const activeTab=ref('all');const keyword=ref('');const taskType=ref('');const rows=ref<any[]>([]);const warehouses=ref<any[]>([]);const users=ref<any[]>([]);const loading=ref(false);const submitting=ref(false);const page=ref(1);const pageSize=ref(20);const total=ref(0);const createVisible=ref(false);const assignVisible=ref(false);const currentTask=ref<any>();const assigneeId=ref<number>();const form=reactive({taskType:'PUTAWAY',warehouseId:undefined as number|undefined,sourceOrderNo:'',priority:0,remark:''})
const loadData=async()=>{loading.value=true;try{const res=await taskApi.listTasks({page:page.value,pageSize:pageSize.value,keyword:keyword.value,taskType:taskType.value,status:activeTab.value==='all'?undefined:activeTab.value});rows.value=res.data?.records||[];total.value=Number(res.data?.total||0)}finally{loading.value=false}}
const search=()=>{page.value=1;loadData()};const changeTab=()=>search();const typeText=(v:string)=>taskTypes.find(i=>i.value===v)?.label||v;const warehouseName=(id:number)=>warehouses.value.find(w=>w.id===id)?.warehouseName||id||'-';const priorityInfo=(v:number)=>[{text:'普通',type:'info'},{text:'优先',type:'warning'},{text:'紧急',type:'danger'}][v]||{text:String(v),type:'info'};const statusInfo=(v:string)=>({PENDING:{text:'待分配',type:'info'},IN_PROGRESS:{text:'进行中',type:'warning'},COMPLETED:{text:'已完成',type:'success'}}[v]||{text:v,type:'info'})
const openCreate=()=>{Object.assign(form,{taskType:'PUTAWAY',warehouseId:undefined,sourceOrderNo:'',priority:0,remark:''});createVisible.value=true};const createTask=async()=>{if(!form.warehouseId)return ElMessage.warning('请选择仓库');submitting.value=true;try{await taskApi.createTask(form);ElMessage.success('任务创建成功');createVisible.value=false;await loadData()}finally{submitting.value=false}}
const openAssign=(row:any)=>{currentTask.value=row;assigneeId.value=undefined;assignVisible.value=true};const assign=async()=>{if(!currentTask.value||!assigneeId.value)return ElMessage.warning('请选择执行人');submitting.value=true;try{await taskApi.assignTask(currentTask.value.id,assigneeId.value);ElMessage.success('分配成功');assignVisible.value=false;await loadData()}finally{submitting.value=false}};const complete=async(row:any)=>{try{await ElMessageBox.confirm(`确认任务“${row.taskNo}”已经完成？`,'完成确认',{type:'warning'});await taskApi.completeTask(row.id);ElMessage.success('任务已完成');await loadData()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error('操作失败')}}
onMounted(async()=>{const [w,u]=await Promise.all([warehouseApi.listWarehouses({page:1,pageSize:1000}),userApi.listUsers({page:1,pageSize:1000})]);warehouses.value=w.data?.records||[];users.value=(u.data?.records||[]).filter((item:any)=>item.status===1);await loadData()})
</script>
