<template>
  <div class="page-container" v-loading="loading">
    <div class="page-header header"><div><h1 class="page-title">盘点执行</h1><p class="page-subtitle">录入实盘数量、核对差异并调整库存</p></div><div class="actions"><el-button @click="router.back()">返回</el-button><el-button v-if="stocktake.status==='CREATED'" type="primary" :loading="submitting" @click="start">开始盘点</el-button><el-button v-if="stocktake.status==='IN_PROGRESS'" type="success" :loading="submitting" :disabled="remaining>0" @click="complete">完成盘点</el-button></div></div>
    <el-result v-if="!loading&&failed" icon="error" title="加载失败"><template #extra><el-button type="primary" @click="loadData">重新加载</el-button></template></el-result>
    <template v-else>
      <div class="card summary"><el-descriptions :column="4" border><el-descriptions-item label="盘点单号">{{stocktake.stocktakeNo||'-'}}</el-descriptions-item><el-descriptions-item label="仓库">{{stocktake.warehouseName||stocktake.warehouseId||'-'}}</el-descriptions-item><el-descriptions-item label="类型">{{stocktake.stocktakeType==='FULL'?'全仓盘点':'抽样盘点'}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="status.type">{{status.text}}</el-tag></el-descriptions-item></el-descriptions><div class="progress-row"><el-progress :percentage="progress" :status="progress===100?'success':undefined"/><span>已盘 {{counted}} / {{items.length}}，差异 {{diffCount}} 项</span></div></div>
      <div class="card"><div class="toolbar"><div class="section-title">盘点明细</div><el-tag v-if="remaining>0&&stocktake.status==='IN_PROGRESS'" type="warning">还有 {{remaining}} 项未盘</el-tag></div>
        <el-table :data="items" border stripe empty-text="暂无盘点明细"><el-table-column prop="locationCode" label="库位" width="120"><template #default="{row}">{{row.locationCode||row.locationId||'-'}}</template></el-table-column><el-table-column prop="skuCode" label="SKU" width="150"><template #default="{row}">{{row.skuCode||row.skuId}}</template></el-table-column><el-table-column prop="productName" label="商品" min-width="160"/><el-table-column prop="batchNo" label="批次" width="140"/><el-table-column prop="systemQty" label="账面数量" width="100" align="right"/><el-table-column label="实盘数量" width="170"><template #default="{row}"><el-input-number v-if="stocktake.status==='IN_PROGRESS'" v-model="row.inputQty" :min="0" :precision="0" size="small"/><span v-else>{{row.actualQty??'-'}}</span></template></el-table-column><el-table-column label="差异" width="90" align="right"><template #default="{row}"><span :class="difference(row)>0?'positive':difference(row)<0?'negative':''">{{row.actualQty==null?'-':formatDiff(difference(row))}}</span></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button v-if="stocktake.status==='IN_PROGRESS'" type="primary" link :loading="row.saving" @click="save(row)">{{row.status==='COUNTED'?'更新':'保存'}}</el-button><el-tag v-else-if="row.status==='ADJUSTED'" type="warning">已调整</el-tag><el-tag v-else-if="row.status==='COUNTED'" type="success">已盘</el-tag></template></el-table-column></el-table>
      </div>
    </template>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { stocktakeApi } from '@/api'
const route=useRoute(),router=useRouter(),id=Number(route.params.id),loading=ref(false),submitting=ref(false),failed=ref(false),stocktake=ref<Record<string,any>>({}),items=ref<any[]>([])
const statusMap:Record<string,{text:string;type:''|'success'|'warning'|'info'}>={CREATED:{text:'待开始',type:'info'},IN_PROGRESS:{text:'盘点中',type:'warning'},COMPLETED:{text:'已完成',type:'success'}}
const status=computed(()=>statusMap[stocktake.value.status]||{text:stocktake.value.status||'-',type:'info' as const}),counted=computed(()=>items.value.filter(x=>['COUNTED','ADJUSTED'].includes(x.status)).length),remaining=computed(()=>items.value.length-counted.value),diffCount=computed(()=>items.value.filter(x=>x.actualQty!=null&&x.actualQty!==x.systemQty).length),progress=computed(()=>items.value.length?Math.round(counted.value/items.value.length*100):0)
const difference=(row:any)=>(row.actualQty??row.systemQty)-row.systemQty,formatDiff=(v:number)=>v>0?`+${v}`:`${v}`
async function loadData(){loading.value=true;failed.value=false;try{const[s,i]=await Promise.all([stocktakeApi.getStocktakeById(id),stocktakeApi.getStocktakeItems(id)]);stocktake.value=s.data||{};items.value=(i.data||[]).map((x:any)=>({...x,inputQty:x.actualQty??x.systemQty,saving:false}))}catch{failed.value=true}finally{loading.value=false}}
async function start(){await ElMessageBox.confirm('开始后将以当前库存快照为基准录入实盘数量。','开始盘点',{type:'warning'});submitting.value=true;try{await stocktakeApi.startStocktake(id);ElMessage.success('盘点已开始');await loadData()}finally{submitting.value=false}}
async function save(row:any){if(row.inputQty==null||row.inputQty<0){ElMessage.warning('请输入有效的实盘数量');return}row.saving=true;try{await stocktakeApi.countStocktakeItem(row.id,row.inputQty);ElMessage.success('盘点结果已保存');await loadData()}finally{row.saving=false}}
async function complete(){await ElMessageBox.confirm(diffCount.value?`存在 ${diffCount.value} 项差异，完成后将调整库存，是否继续？`:'确认完成本次盘点？','完成盘点',{type:'warning'});submitting.value=true;try{await stocktakeApi.completeStocktake(id);ElMessage.success('盘点已完成，库存差异已处理');await loadData()}finally{submitting.value=false}}
onMounted(loadData)
</script>
<style scoped>.header,.actions,.toolbar,.progress-row{display:flex;align-items:center;justify-content:space-between;gap:16px}.summary{margin-bottom:20px}.progress-row{margin-top:20px}.progress-row :deep(.el-progress){flex:1}.section-title{font-size:16px;font-weight:600}.toolbar{margin-bottom:16px}.positive{color:#16a34a;font-weight:600}.negative{color:#dc2626;font-weight:600}</style>
