<template>
  <div class="page-container" v-loading="loading">
    <div class="page-header map-header"><div><h1 class="page-title">库位状态地图</h1><p class="page-subtitle">{{warehouse.warehouseName||'仓库'}} · 按库区、货架、层位查看空间占用</p></div><div class="header-actions"><el-button @click="router.back()">返回</el-button><el-button type="primary" @click="loadMap">刷新地图</el-button></div></div>
    <el-result v-if="!loading&&failed" icon="error" title="地图加载失败"><template #extra><el-button type="primary" @click="loadMap">重新加载</el-button></template></el-result>
    <template v-else>
      <div class="metrics"><div class="metric-card"><div class="metric-label">库区</div><div class="metric-value">{{zones.length}}</div></div><div class="metric-card"><div class="metric-label">货架</div><div class="metric-value">{{rackCount}}</div></div><div class="metric-card"><div class="metric-label">库位</div><div class="metric-value">{{locationCount}}</div></div><div class="metric-card"><div class="metric-label">空间利用率</div><div class="metric-value accent">{{utilization}}%</div></div></div>
      <div class="legend card"><span v-for="item in legend" :key="item.status"><i :class="`dot status-${item.status}`"></i>{{item.text}} {{statusCounts[item.status]||0}}</span></div>
      <el-empty v-if="!zones.length&&!loading" description="该仓库尚未配置库区"/>
      <el-tabs v-else v-model="activeZone" class="zone-tabs"><el-tab-pane v-for="zone in zones" :key="zone.id" :label="`${zone.zoneName} (${zone.racks.length})`" :name="String(zone.id)">
        <div v-if="!zone.racks.length" class="card"><el-empty description="该库区尚未配置货架"/></div>
        <div v-else class="rack-list"><article v-for="rack in zone.racks" :key="rack.id" class="card rack-card"><div class="rack-head"><div><strong>{{rack.rackName}}</strong><small>{{rack.rackCode}} · {{rack.floorCount||floorCount(rack)}} 层</small></div><el-progress type="circle" :width="54" :stroke-width="5" :percentage="rackRate(rack)"/></div>
          <div v-if="!rack.locations.length" class="empty-rack">暂无库位</div><div v-else class="location-map"><div v-for="floor in floors(rack)" :key="floor" class="floor-row"><span class="floor-label">{{floor}}F</span><button v-for="location in locationsAtFloor(rack,floor)" :key="location.id" class="location-cell" :class="`status-${displayStatus(location)}`" @click="selected=location"><b>{{location.locationCode}}</b><small>{{location.usedCapacity||0}} / {{location.maxCapacity||0}}</small><el-progress :percentage="locationRate(location)" :show-text="false" :stroke-width="4"/></button></div></div>
        </article></div>
      </el-tab-pane></el-tabs>
    </template>
    <el-drawer v-model="detailDrawer" title="库位详情" size="380px"><el-descriptions :column="1" border><el-descriptions-item label="库位编码">{{selected?.locationCode}}</el-descriptions-item><el-descriptions-item label="所属仓库">{{warehouse.warehouseName}}</el-descriptions-item><el-descriptions-item label="层 / 位">{{selected?.floor}} / {{selected?.position}}</el-descriptions-item><el-descriptions-item label="库位类型">{{selected?.locationType||'-'}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusTag(displayStatus(selected))">{{statusText(displayStatus(selected))}}</el-tag></el-descriptions-item><el-descriptions-item label="已用容量">{{selected?.usedCapacity||0}}</el-descriptions-item><el-descriptions-item label="最大容量">{{selected?.maxCapacity||0}}</el-descriptions-item><el-descriptions-item label="最大承重">{{selected?.maxWeight?`${selected.maxWeight} kg`:'-'}}</el-descriptions-item></el-descriptions></el-drawer>
  </div>
</template>
<script setup lang="ts">
import{computed,onMounted,ref,watch}from'vue';import{useRoute,useRouter}from'vue-router';import{warehouseApi,warehouseStructureApi}from'@/api';
const route=useRoute(),router=useRouter(),warehouseId=Number(route.params.id),loading=ref(false),failed=ref(false),warehouse=ref<any>({}),zones=ref<any[]>([]),activeZone=ref(''),selected=ref<any>();
const legend=[{status:'EMPTY',text:'空闲'},{status:'AVAILABLE',text:'可用'},{status:'PARTIAL',text:'部分占用'},{status:'FULL',text:'已满'},{status:'LOCKED',text:'锁定'},{status:'DISABLED',text:'禁用'}],allLocations=computed(()=>zones.value.flatMap(z=>z.racks.flatMap((r:any)=>r.locations))),rackCount=computed(()=>zones.value.reduce((n,z)=>n+z.racks.length,0)),locationCount=computed(()=>allLocations.value.length),usedTotal=computed(()=>allLocations.value.reduce((n,l)=>n+(l.usedCapacity||0),0)),capacityTotal=computed(()=>allLocations.value.reduce((n,l)=>n+(l.maxCapacity||0),0)),utilization=computed(()=>capacityTotal.value?Math.round(usedTotal.value/capacityTotal.value*100):0),statusCounts=computed(()=>Object.fromEntries(legend.map(x=>[x.status,allLocations.value.filter(l=>displayStatus(l)===x.status).length]))),detailDrawer=computed({get:()=>!!selected.value,set:v=>{if(!v)selected.value=null}});
async function loadMap(){loading.value=true;failed.value=false;try{const[w,z]=await Promise.all([warehouseApi.getWarehouseById(warehouseId),warehouseStructureApi.listZones(warehouseId)]);warehouse.value=w.data||{};const loaded=await Promise.all((z.data||[]).map(async(zone:any)=>{const rr=await warehouseStructureApi.listRacks(zone.id);const racks=await Promise.all((rr.data||[]).map(async(rack:any)=>{const ll=await warehouseStructureApi.listLocations(rack.id);return{...rack,locations:ll.data||[]}}));return{...zone,racks}}));zones.value=loaded;if(!loaded.some(z=>String(z.id)===activeZone.value))activeZone.value=loaded[0]?String(loaded[0].id):''}catch{failed.value=true}finally{loading.value=false}}
const displayStatus=(l:any)=>!l?'EMPTY':l.isDisabled===1?'DISABLED':l.status||'EMPTY',locationRate=(l:any)=>l.maxCapacity?Math.min(100,Math.round((l.usedCapacity||0)/l.maxCapacity*100)):0,rackRate=(r:any)=>{const c=r.locations.reduce((n:number,l:any)=>n+(l.maxCapacity||0),0),u=r.locations.reduce((n:number,l:any)=>n+(l.usedCapacity||0),0);return c?Math.round(u/c*100):0},floorCount=(r:any)=>Math.max(0,...r.locations.map((l:any)=>l.floor||0)),floors=(r:any)=>Array.from(new Set<number>(r.locations.map((l:any)=>l.floor||1))).sort((a,b)=>b-a),locationsAtFloor=(r:any,f:number)=>r.locations.filter((l:any)=>(l.floor||1)===f).sort((a:any,b:any)=>(a.position||0)-(b.position||0));
const statusText=(s:string)=>Object.fromEntries(legend.map(x=>[x.status,x.text]))[s]||s,statusTag=(s:string)=>({EMPTY:'info',AVAILABLE:'success',PARTIAL:'warning',FULL:'danger',LOCKED:'warning',DISABLED:'info'}as Record<string,any>)[s]||'info';watch(()=>route.params.id,loadMap);onMounted(loadMap)
</script>
<style scoped>.map-header,.header-actions,.legend,.rack-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:16px}.accent{color:#2563eb}.legend{justify-content:flex-start;flex-wrap:wrap;margin-bottom:16px;padding:14px 20px}.legend span{display:flex;align-items:center;gap:7px;margin-right:18px;font-size:13px}.dot{width:11px;height:11px;border-radius:3px}.rack-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.rack-card{min-width:0}.rack-head{margin-bottom:18px}.rack-head>div{display:flex;flex-direction:column;gap:5px}.rack-head small,.location-cell small{color:var(--text-secondary)}.location-map{display:flex;flex-direction:column;gap:8px}.floor-row{display:grid;grid-template-columns:38px repeat(auto-fit,minmax(105px,1fr));gap:8px}.floor-label{display:flex;align-items:center;justify-content:center;font-weight:700;color:#64748b}.location-cell{border:1px solid transparent;border-radius:8px;padding:10px;text-align:left;display:flex;flex-direction:column;gap:6px;cursor:pointer;transition:.18s}.location-cell:hover{transform:translateY(-2px);box-shadow:0 5px 14px #0f172a18}.status-EMPTY{background:#f8fafc;border-color:#cbd5e1}.status-AVAILABLE{background:#ecfdf5;border-color:#86efac}.status-PARTIAL{background:#fffbeb;border-color:#fcd34d}.status-FULL{background:#fef2f2;border-color:#fca5a5}.status-LOCKED{background:#f5f3ff;border-color:#c4b5fd}.status-DISABLED{background:#e5e7eb;border-color:#9ca3af;color:#6b7280}.empty-rack{padding:35px;text-align:center;color:#94a3b8}@media(max-width:1100px){.rack-list{grid-template-columns:1fr}}@media(max-width:760px){.metrics{grid-template-columns:1fr 1fr}.floor-row{grid-template-columns:34px 1fr 1fr}}</style>
