<template>
  <div class="page-container">
    <div class="page-header"><h1 class="page-title">仓库中心</h1><p class="page-subtitle">管理仓库、库区、货架和库位基础数据</p></div>
    <div class="card">
      <div class="search-bar"><el-input v-model="keyword" placeholder="搜索仓库编码或名称" prefix-icon="Search" clearable @keyup.enter="loadWarehouses"/><el-button type="primary" @click="loadWarehouses">查询</el-button><el-button type="success" @click="editWarehouse()"><el-icon><Plus/></el-icon>新增仓库</el-button></div>
      <el-table :data="warehouses" stripe border v-loading="loading" empty-text="暂无仓库"><el-table-column prop="warehouseCode" label="仓库编码" width="130"/><el-table-column prop="warehouseName" label="仓库名称" min-width="150"/><el-table-column prop="address" label="地址" min-width="180"/><el-table-column prop="contactPerson" label="联系人" width="100"/><el-table-column prop="phone" label="联系电话" width="130"/><el-table-column label="容量" width="170"><template #default="{row}"><el-progress :percentage="capacityRate(row)"/></template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status===1?'success':'danger'">{{row.status===1?'启用':'禁用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{row}"><el-button type="primary" link @click="openStructure(row)">结构</el-button><el-button type="success" link @click="$router.push(`/warehouse/${row.id}/map`)">地图</el-button><el-button type="primary" link @click="editWarehouse(row)">编辑</el-button><el-button type="danger" link @click="removeWarehouse(row)">删除</el-button></template></el-table-column></el-table>
    </div>

    <el-dialog v-model="warehouseDialog" :title="warehouseForm.id?'编辑仓库':'新增仓库'" width="600px"><el-form ref="warehouseFormRef" :model="warehouseForm" :rules="warehouseRules" label-width="90px"><div class="grid"><el-form-item label="仓库编码" prop="warehouseCode"><el-input v-model.trim="warehouseForm.warehouseCode" :disabled="!!warehouseForm.id"/></el-form-item><el-form-item label="仓库名称" prop="warehouseName"><el-input v-model.trim="warehouseForm.warehouseName"/></el-form-item><el-form-item label="联系人"><el-input v-model.trim="warehouseForm.contactPerson"/></el-form-item><el-form-item label="联系电话"><el-input v-model.trim="warehouseForm.phone"/></el-form-item><el-form-item label="总容量" prop="totalCapacity"><el-input-number v-model="warehouseForm.totalCapacity" :min="0" :precision="0"/></el-form-item><el-form-item label="状态"><el-switch v-model="warehouseForm.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form-item></div><el-form-item label="地址"><el-input v-model.trim="warehouseForm.address"/></el-form-item></el-form><template #footer><el-button @click="warehouseDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveWarehouse">保存</el-button></template></el-dialog>

    <el-drawer v-model="structureDrawer" :title="`${currentWarehouse?.warehouseName||''} · 仓库结构`" size="82%" destroy-on-close><div class="structure-grid">
      <section><div class="section-head"><b>库区</b><el-button type="primary" link @click="editZone()">新增</el-button></div><el-table :data="zones" highlight-current-row border @current-change="selectZone"><el-table-column prop="zoneCode" label="编码"/><el-table-column prop="zoneName" label="名称"/><el-table-column prop="zoneType" label="类型"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click.stop="editZone(row)">编辑</el-button><el-button link type="danger" @click.stop="removeNode('zone',row)">删</el-button></template></el-table-column></el-table></section>
      <section><div class="section-head"><b>货架 {{currentZone?`· ${currentZone.zoneName}`:''}}</b><el-button type="primary" link :disabled="!currentZone" @click="editRack()">新增</el-button></div><el-empty v-if="!currentZone" description="请先选择库区"/><el-table v-else :data="racks" highlight-current-row border @current-change="selectRack"><el-table-column prop="rackCode" label="编码"/><el-table-column prop="rackName" label="名称"/><el-table-column prop="floorCount" label="层数" width="65"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click.stop="editRack(row)">编辑</el-button><el-button link type="danger" @click.stop="removeNode('rack',row)">删</el-button></template></el-table-column></el-table></section>
      <section><div class="section-head"><b>库位 {{currentRack?`· ${currentRack.rackName}`:''}}</b><el-button type="primary" link :disabled="!currentRack" @click="editLocation()">新增</el-button></div><el-empty v-if="!currentRack" description="请先选择货架"/><el-table v-else :data="locations" border><el-table-column prop="locationCode" label="编码"/><el-table-column label="坐标" width="80"><template #default="{row}">{{row.floor}}-{{row.position}}</template></el-table-column><el-table-column prop="maxCapacity" label="容量" width="70"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="editLocation(row)">编辑</el-button><el-button link type="danger" @click="removeNode('location',row)">删</el-button></template></el-table-column></el-table></section>
    </div></el-drawer>

    <el-dialog v-model="nodeDialog" :title="nodeTitle" width="520px" append-to-body><el-form :model="nodeForm" label-width="90px"><template v-if="nodeType==='zone'"><el-form-item label="库区编码"><el-input v-model.trim="nodeForm.zoneCode"/></el-form-item><el-form-item label="库区名称"><el-input v-model.trim="nodeForm.zoneName"/></el-form-item><el-form-item label="库区类型"><el-select v-model="nodeForm.zoneType"><el-option label="存储区" value="STORAGE"/><el-option label="收货区" value="RECEIVING"/><el-option label="拣货区" value="PICKING"/><el-option label="退货区" value="RETURN"/></el-select></el-form-item><el-form-item label="温度要求"><el-input v-model.trim="nodeForm.temperature"/></el-form-item></template><template v-else-if="nodeType==='rack'"><el-form-item label="货架编码"><el-input v-model.trim="nodeForm.rackCode"/></el-form-item><el-form-item label="货架名称"><el-input v-model.trim="nodeForm.rackName"/></el-form-item><el-form-item label="层数"><el-input-number v-model="nodeForm.floorCount" :min="1"/></el-form-item></template><template v-else><el-form-item label="库位编码"><el-input v-model.trim="nodeForm.locationCode"/></el-form-item><div class="grid"><el-form-item label="层"><el-input-number v-model="nodeForm.floor" :min="1"/></el-form-item><el-form-item label="位"><el-input-number v-model="nodeForm.position" :min="1"/></el-form-item><el-form-item label="最大容量"><el-input-number v-model="nodeForm.maxCapacity" :min="1"/></el-form-item><el-form-item label="库位类型"><el-select v-model="nodeForm.locationType"><el-option label="普通" value="NORMAL"/><el-option label="拣货" value="PICKING"/><el-option label="暂存" value="STAGING"/></el-select></el-form-item></div></template></el-form><template #footer><el-button @click="nodeDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveNode">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox,type FormInstance,type FormRules}from'element-plus';import{Plus}from'@element-plus/icons-vue';import{warehouseApi,warehouseStructureApi}from'@/api';
const loading=ref(false),saving=ref(false),keyword=ref(''),warehouses=ref<any[]>([]),warehouseDialog=ref(false),warehouseFormRef=ref<FormInstance>(),structureDrawer=ref(false),currentWarehouse=ref<any>(),zones=ref<any[]>([]),racks=ref<any[]>([]),locations=ref<any[]>([]),currentZone=ref<any>(),currentRack=ref<any>(),nodeDialog=ref(false),nodeType=ref<'zone'|'rack'|'location'>('zone'),nodeTitle=ref(''),nodeForm=reactive<Record<string,any>>({});
const warehouseForm=reactive({id:null as number|null,warehouseCode:'',warehouseName:'',address:'',contactPerson:'',phone:'',totalCapacity:0,usedCapacity:0,status:1}),warehouseRules:FormRules={warehouseCode:[{required:true,message:'请输入仓库编码',trigger:'blur'}],warehouseName:[{required:true,message:'请输入仓库名称',trigger:'blur'}],totalCapacity:[{required:true,message:'请输入总容量',trigger:'blur'}]};
const capacityRate=(r:any)=>r.totalCapacity?Math.min(100,Math.round((r.usedCapacity||0)/r.totalCapacity*100)):0;
async function loadWarehouses(){loading.value=true;try{const r=await warehouseApi.listWarehouses({page:1,pageSize:1000,keyword:keyword.value||undefined});warehouses.value=r.data?.records||r.data||[]}finally{loading.value=false}}
function editWarehouse(row?:any){Object.assign(warehouseForm,row?{...row}:{id:null,warehouseCode:'',warehouseName:'',address:'',contactPerson:'',phone:'',totalCapacity:0,usedCapacity:0,status:1});warehouseDialog.value=true}
async function saveWarehouse(){if(!await warehouseFormRef.value?.validate())return;saving.value=true;try{warehouseForm.id?await warehouseApi.updateWarehouse(warehouseForm.id,warehouseForm):await warehouseApi.createWarehouse(warehouseForm);ElMessage.success('仓库保存成功');warehouseDialog.value=false;await loadWarehouses()}finally{saving.value=false}}
async function removeWarehouse(row:any){await ElMessageBox.confirm(`确定删除仓库 ${row.warehouseName}？仅空仓库允许删除。`,'删除仓库',{type:'warning'});await warehouseApi.deleteWarehouse(row.id);ElMessage.success('删除成功');await loadWarehouses()}
async function openStructure(row:any){currentWarehouse.value=row;structureDrawer.value=true;currentZone.value=null;currentRack.value=null;racks.value=[];locations.value=[];const r=await warehouseStructureApi.listZones(row.id);zones.value=r.data||[]}
async function selectZone(row:any){currentZone.value=row;currentRack.value=null;locations.value=[];if(row){const r=await warehouseStructureApi.listRacks(row.id);racks.value=r.data||[]}}
async function selectRack(row:any){currentRack.value=row;if(row){const r=await warehouseStructureApi.listLocations(row.id);locations.value=r.data||[]}}
function openNode(type:'zone'|'rack'|'location',row?:any){nodeType.value=type;nodeTitle.value=`${row?'编辑':'新增'}${type==='zone'?'库区':type==='rack'?'货架':'库位'}`;Object.keys(nodeForm).forEach(k=>delete nodeForm[k]);Object.assign(nodeForm,row?{...row}:type==='zone'?{warehouseId:currentWarehouse.value.id,zoneCode:'',zoneName:'',zoneType:'STORAGE',temperature:'',status:1}:type==='rack'?{zoneId:currentZone.value.id,rackCode:'',rackName:'',floorCount:1,status:1}:{rackId:currentRack.value.id,zoneId:currentZone.value.id,warehouseId:currentWarehouse.value.id,locationCode:'',floor:1,position:1,locationType:'NORMAL',maxCapacity:100,usedCapacity:0,status:'EMPTY',isDisabled:0});nodeDialog.value=true}
const editZone=(r?:any)=>openNode('zone',r),editRack=(r?:any)=>openNode('rack',r),editLocation=(r?:any)=>openNode('location',r);
async function saveNode(){const required=nodeType.value==='zone'?['zoneCode','zoneName']:nodeType.value==='rack'?['rackCode','rackName']:['locationCode'];if(required.some(k=>!nodeForm[k])){ElMessage.warning('请填写编码和名称等必填信息');return}saving.value=true;try{const api:any=warehouseStructureApi;const name=nodeType.value==='zone'?'Zone':nodeType.value==='rack'?'Rack':'Location';nodeForm.id?await api[`update${name}`](nodeForm.id,nodeForm):await api[`create${name}`](nodeForm);ElMessage.success('保存成功');nodeDialog.value=false;if(nodeType.value==='zone')await openStructure(currentWarehouse.value);else if(nodeType.value==='rack')await selectZone(currentZone.value);else await selectRack(currentRack.value)}finally{saving.value=false}}
async function removeNode(type:'zone'|'rack'|'location',row:any){await ElMessageBox.confirm('确定删除？存在下级结构或库存时应先清理。','删除确认',{type:'warning'});const api:any=warehouseStructureApi,name=type==='zone'?'Zone':type==='rack'?'Rack':'Location';await api[`delete${name}`](row.id);ElMessage.success('删除成功');if(type==='zone')await openStructure(currentWarehouse.value);else if(type==='rack')await selectZone(currentZone.value);else await selectRack(currentRack.value)}
onMounted(loadWarehouses)
</script>
<style scoped>.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.grid :deep(.el-select){width:100%}.structure-grid{display:grid;grid-template-columns:1fr 1fr 1.25fr;gap:16px}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.structure-grid section{min-width:0}.structure-grid :deep(.el-table){height:calc(100vh - 150px)}@media(max-width:1100px){.structure-grid{grid-template-columns:1fr}.structure-grid :deep(.el-table){height:auto}}</style>
