<template>
  <div class="page-container">
    <div class="page-header"><h1 class="page-title">出库管理</h1><p class="page-subtitle">管理销售出库、生产领料和其他出库业务</p></div>
    <div class="metrics-grid"><div v-for="m in metrics" :key="m.label" class="metric-card"><div class="metric-label">{{m.label}}</div><div class="metric-value" :style="{color:m.color}">{{m.value}}</div></div></div>
    <div class="card">
      <el-tabs v-model="activeTab"><el-tab-pane label="全部" name="all"/><el-tab-pane label="待审核" name="CREATED"/><el-tab-pane label="待拣货" name="APPROVED"/><el-tab-pane label="拣货中" name="PICKING"/><el-tab-pane label="已完成" name="COMPLETED"/><el-tab-pane label="已取消" name="CANCELLED"/></el-tabs>
      <div class="search-bar"><el-input v-model="keyword" placeholder="搜索出库单号" prefix-icon="Search" clearable @keyup.enter="loadData"/><el-button type="primary" @click="loadData">查询</el-button><el-button type="success" @click="openCreate"><el-icon><Plus/></el-icon> 新建出库单</el-button></div>
      <el-table :data="tableData" stripe border v-loading="loading" empty-text="暂无符合条件的出库单">
        <el-table-column prop="orderNo" label="出库单号" width="170"/><el-table-column prop="orderType" label="类型" width="110"><template #default="{row}">{{typeText[row.orderType]||row.orderType}}</template></el-table-column><el-table-column prop="customerName" label="客户/部门" min-width="150"/><el-table-column prop="warehouseName" label="仓库" min-width="130"><template #default="{row}">{{row.warehouseName||row.warehouseId||'-'}}</template></el-table-column><el-table-column prop="totalQty" label="数量" width="80" align="right"/><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag :type="statusInfo(row.status).type">{{statusInfo(row.status).text}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="210" fixed="right"><template #default="{row}"><el-button type="primary" link @click="viewDetail(row)">查看</el-button><el-button v-if="row.status==='CREATED'" type="primary" link @click="approve(row)">审核</el-button><el-button v-if="row.status==='APPROVED'" type="warning" link @click="pick(row)">拣货</el-button><el-button v-if="['PICKING','CHECKING'].includes(row.status)" type="success" link @click="ship(row)">发货</el-button></template></el-table-column>
      </el-table><el-pagination v-if="total>pageSize" v-model:current-page="page" :page-size="pageSize" :total="total" layout="total, prev, pager, next" class="pagination" @current-change="loadData"/>
    </div>
    <el-dialog v-model="dialogVisible" title="新建出库单" width="760px" destroy-on-close>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="100px">
        <div class="form-grid"><el-form-item label="出库类型" prop="orderType"><el-select v-model="form.orderType"><el-option v-for="(text,value) in typeText" :key="value" :label="text" :value="value"/></el-select></el-form-item><el-form-item label="出库仓库" prop="warehouseId"><el-select v-model="form.warehouseId" filterable><el-option v-for="w in warehouses" :key="w.id" :label="w.warehouseName" :value="w.id"/></el-select></el-form-item><el-form-item label="客户/部门" prop="customerName"><el-input v-model.trim="form.customerName" maxlength="100" show-word-limit/></el-form-item><el-form-item label="预计出库" prop="expectedDate"><el-date-picker v-model="form.expectedDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></div>
        <el-form-item label="备注"><el-input v-model.trim="form.remark" type="textarea" :rows="2" maxlength="200" show-word-limit/></el-form-item>
        <div class="items-title"><span>商品明细</span><el-button type="primary" link @click="addItem"><el-icon><Plus/></el-icon>添加商品</el-button></div>
        <div v-for="(item,index) in form.items" :key="item.key" class="item-row"><el-form-item label="SKU" :prop="`items.${index}.skuId`" :rules="[{required:true,message:'请选择SKU',trigger:'change'}]"><el-select v-model="item.skuId" filterable><el-option v-for="sku in skus" :key="sku.id" :label="`${sku.skuCode} · ${sku.productName||''} ${sku.specification||''}`" :value="sku.id"/></el-select></el-form-item><el-form-item label="数量" :prop="`items.${index}.requiredQty`" :rules="[{required:true,message:'请输入数量',trigger:'blur'}]"><el-input-number v-model="item.requiredQty" :min="1" :precision="0"/></el-form-item><el-button v-if="form.items.length>1" type="danger" link @click="form.items.splice(index,1)">删除</el-button></div>
      </el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">创建出库单</el-button></template>
    </el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage,ElMessageBox,type FormInstance,type FormRules } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { outboundApi,productReferenceApi,warehouseApi } from '@/api'
const router=useRouter(),loading=ref(false),submitting=ref(false),dialogVisible=ref(false),tableData=ref<any[]>([]),allOrders=ref<any[]>([]),warehouses=ref<any[]>([]),skus=ref<any[]>([]),activeTab=ref('all'),keyword=ref(''),page=ref(1),pageSize=20,total=ref(0),formRef=ref<FormInstance>()
const typeText:Record<string,string>={SALE_OUT:'销售出库',MATERIAL_OUT:'生产领料',TRANSFER_OUT:'调拨出库',RETURN_OUT:'退货出库',OTHER_OUT:'其他出库'}
const statusMap:Record<string,{text:string;type:''|'success'|'warning'|'info'|'danger'}>={CREATED:{text:'待审核',type:'info'},APPROVED:{text:'待拣货',type:''},PICKING:{text:'拣货中',type:'warning'},CHECKING:{text:'复核中',type:'warning'},COMPLETED:{text:'已完成',type:'success'},CANCELLED:{text:'已取消',type:'danger'}}
const statusInfo=(s:string)=>statusMap[s]||{text:s,type:'info' as const}
const form=reactive({orderType:'SALE_OUT',warehouseId:null as number|null,customerName:'',expectedDate:'',remark:'',items:[] as Array<{key:number;skuId:number|null;requiredQty:number}>})
const rules:FormRules={orderType:[{required:true,message:'请选择出库类型',trigger:'change'}],warehouseId:[{required:true,message:'请选择仓库',trigger:'change'}],customerName:[{required:true,message:'请输入客户或领用部门',trigger:'blur'}],expectedDate:[{required:true,message:'请选择预计出库日期',trigger:'change'}]}
const metrics=computed(()=>[{label:'待审核',value:allOrders.value.filter(x=>x.status==='CREATED').length,color:'#2563EB'},{label:'待拣货',value:allOrders.value.filter(x=>x.status==='APPROVED').length,color:'#D97706'},{label:'执行中',value:allOrders.value.filter(x=>['PICKING','CHECKING'].includes(x.status)).length,color:'#7C3AED'},{label:'已完成',value:allOrders.value.filter(x=>x.status==='COMPLETED').length,color:'#16A34A'}])
async function loadData(){loading.value=true;try{const params={page:page.value,pageSize,keyword:keyword.value||undefined,status:activeTab.value==='all'?undefined:activeTab.value};const[list,all]=await Promise.all([outboundApi.listOutboundOrders(params),outboundApi.listOutboundOrders({page:1,pageSize:1000})]);tableData.value=list.data?.records||[];total.value=list.data?.total||0;allOrders.value=all.data?.records||[]}finally{loading.value=false}}
let key=0;const addItem=()=>form.items.push({key:++key,skuId:null,requiredQty:1})
async function openCreate(){Object.assign(form,{orderType:'SALE_OUT',warehouseId:null,customerName:'',expectedDate:'',remark:''});form.items=[];addItem();dialogVisible.value=true;try{const[w,s]=await Promise.all([warehouseApi.listWarehouses({page:1,pageSize:1000}),productReferenceApi.listSkus()]);warehouses.value=w.data?.records||w.data||[];skus.value=s.data||[]}catch{dialogVisible.value=false}}
async function submit(){if(!await formRef.value?.validate())return;const ids=form.items.map(x=>x.skuId);if(new Set(ids).size!==ids.length){ElMessage.warning('同一个SKU请合并为一行');return}submitting.value=true;try{await outboundApi.createOutboundOrder({order:{orderType:form.orderType,warehouseId:form.warehouseId,customerName:form.customerName,expectedDate:form.expectedDate,remark:form.remark},items:form.items.map(({skuId,requiredQty})=>({skuId,requiredQty}))});ElMessage.success('出库单创建成功');dialogVisible.value=false;page.value=1;await loadData()}finally{submitting.value=false}}
const viewDetail=(row:any)=>router.push(`/outbound/${row.id}`)
async function run(row:any,action:()=>Promise<any>,text:string){await ElMessageBox.confirm(`确认对出库单 ${row.orderNo} 执行${text}？`,text,{type:'warning'});await action();ElMessage.success(`${text}成功`);await loadData()}
const approve=(r:any)=>run(r,()=>outboundApi.approveOutboundOrder(r.id),'审核'),pick=(r:any)=>run(r,()=>outboundApi.pickOutboundOrder(r.id),'拣货'),ship=(r:any)=>run(r,()=>outboundApi.shipOutboundOrder(r.id),'发货')
watch(activeTab,()=>{page.value=1;loadData()});onMounted(loadData)
</script>
<style scoped>.metrics-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}.pagination{justify-content:flex-end;margin-top:18px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 20px}.form-grid :deep(.el-select),.form-grid :deep(.el-date-editor){width:100%}.items-title{display:flex;justify-content:space-between;align-items:center;font-weight:600;margin:10px 0}.item-row{display:grid;grid-template-columns:minmax(0,2fr) minmax(180px,1fr) 48px;gap:12px;align-items:start;padding:12px;background:var(--el-fill-color-lighter);border-radius:8px;margin-bottom:10px}.item-row :deep(.el-form-item){margin-bottom:0}.item-row :deep(.el-select){width:100%}@media(max-width:900px){.metrics-grid,.form-grid{grid-template-columns:1fr 1fr}.item-row{grid-template-columns:1fr}}</style>
